# LLM Configuration Structure

# Shared system instructions across all agents
system:
  default_instructions: |
    You are a helpful AI assistant.
    Follow user instructions precisely.
    Be concise and clear in your responses.
  safety_guidelines: |
    Do not generate harmful content.
    Respect user privacy.
    Follow ethical AI principles.

# Configuration for the referee/controller LLM
referee:
  provider: anthropic
  model: claude-3-5-sonnet-20240620
  temperature: 0.7
  max_tokens: 1000
  api_key_env_var: ANTHROPIC_API_KEY
  custom_settings:
    top_p: 0.9
    top_k: 40

# Multiple LLM providers with their models and settings
providers:
  openai:
    api_key_env_var: OPENAI_API_KEY
    base_url: https://api.openai.com/v1
    models:
      gpt-4:
        name: gpt-4-turbo
        temperature: 0.7
        max_tokens: 2000
        custom_settings:
          top_p: 1.0
          frequency_penalty: 0.0
          presence_penalty: 0.0
      gpt-3.5:
        name: gpt-3.5-turbo
        temperature: 0.5
        max_tokens: 1500
        custom_settings:
          top_p: 1.0
      gpt-4o:
        name: gpt-4o
        temperature: 0.8
        max_tokens: 4000
        custom_settings:
          top_p: 0.9
    
  anthropic:
    api_key_env_var: ANTHROPIC_API_KEY
    base_url: https://api.anthropic.com/v1
    models:
      claude-3-opus:
        name: claude-3-opus-20240229
        temperature: 0.7
        max_tokens: 4000
        custom_settings:
          top_p: 0.9
          top_k: 40
      claude-3-sonnet:
        name: claude-3-5-sonnet-20240620
        temperature: 0.6
        max_tokens: 2000
        custom_settings:
          top_p: 0.8
          top_k: 40
      claude-3-haiku:
        name: claude-3-haiku-20240307
        temperature: 0.5
        max_tokens: 1000
        custom_settings:
          top_p: 0.7
          top_k: 40
    
  qwen:
    api_key_env_var: ALIBABA_CLOUD_API_KEY
    base_url: https://dashscope.aliyuncs.com/api/v1
    models:
      qwen-max:
        name: qwen-max
        temperature: 0.7
        max_tokens: 2000
        custom_settings:
          top_p: 0.8
          enable_search: true
      qwen-plus:
        name: qwen-plus
        temperature: 0.6
        max_tokens: 1500
        custom_settings:
          top_p: 0.75
          enable_search: false
    
  openrouter:
    api_key_env_var: OPENROUTER_API_KEY
    base_url: https://openrouter.ai/api/v1
    models:
      llama-3-70b:
        name: meta-llama/llama-3-70b-instruct
        temperature: 0.7
        max_tokens: 4000
        custom_settings:
          top_p: 0.9
          repetition_penalty: 1.0
      mistral-large:
        name: mistralai/mistral-large
        temperature: 0.6
        max_tokens: 32000
        custom_settings:
          top_p: 0.85
          repetition_penalty: 1.05

# Agent-specific configurations
agents:
  chess_master:
    instructions: |
      You are a chess grandmaster assistant.
      Provide strategic analysis and moves.
      Explain chess concepts clearly.
    provider: openai
    model: gpt-4
    temperature: 0.6
    max_tokens: 1000
    
  data_analyst:
    instructions: |
      You are a data analysis specialist.
      Interpret data, create visualizations, and explain insights.
      Be precise with numbers and statistical concepts.
    provider: anthropic
    model: claude-3-opus
    temperature: 0.5
    max_tokens: 2000
    
  creative_writer:
    instructions: |
      You are a creative writing assistant.
      Help with story development, character creation, and prose.
      Encourage creativity while maintaining good narrative structure.
    provider: openrouter
    model: llama-3-70b
    temperature: 0.8
    max_tokens: 1500

# Default settings when not specified
defaults:
  temperature: 0.7
  max_tokens: 1000
  timeout: 120
  retry_attempts: 3

# Global settings
global:
  timeout: 120
  retry_attempts: 3
  cache_responses: true
  cache_ttl: 3600  # in seconds